set_property PACKAGE_PIN Y8 [get_ports clk_200mhz_p]
set_property IOSTANDARD LVCMOS18 [get_ports {trig_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {trig_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {trig_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {trig_out[0]}]
set_property PACKAGE_PIN AB3 [get_ports {trig_out[3]}]
set_property PACKAGE_PIN AA4 [get_ports {trig_out[2]}]
set_property PACKAGE_PIN AA3 [get_ports {trig_out[1]}]
set_property PACKAGE_PIN AB2 [get_ports {trig_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN A16 [get_ports {led[3]}]
set_property PACKAGE_PIN A15 [get_ports {led[2]}]
set_property PACKAGE_PIN B15 [get_ports {led[1]}]
set_property PACKAGE_PIN A14 [get_ports {led[0]}]

create_clock -period 5.000 -name clk_200mhz_p -waveform {0.000 2.500} [get_ports clk_200mhz_p]

set_property DRIVE 12 [get_ports {trig_out[3]}]
set_property DRIVE 12 [get_ports {trig_out[2]}]
set_property DRIVE 12 [get_ports {trig_out[1]}]
set_property DRIVE 12 [get_ports {trig_out[0]}]
